In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [16]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [17]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [18]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [19]:
model = LinearRegression()

In [20]:
model.fit(x, y)

LinearRegression()

In [21]:
model = LinearRegression().fit(x, y)

In [22]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8615939258756775


In [23]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


In [24]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)
print('slope:', new_model.coef_)

intercept: [5.52257928]
slope: [[0.44706965 0.25502548]]


In [25]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [26]:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 5.52257928  5.77760476]
 [ 7.75792752  5.77760476]
 [12.22862401  6.03263024]
 [16.6993205   6.79770668]
 [21.17001699  8.32785957]
 [25.64071348  9.34796149]
 [30.11140997 14.19344564]
 [32.34675821 14.44847112]]


In [30]:
x_new = np.arange(10).reshape((-1, 2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
y_new = model.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
