In [1]:
import numpy as np 


In [2]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [3]:
np.array([5,6,7, 5+7j, "sudh"  , 56.67])

array(['5', '6', '7', '(5+7j)', 'sudh', '56.67'], dtype='<U64')

In [4]:
a = np.array([5,6,7])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([4 , 5,6,7 ] , dtype = complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [7]:
np.array([5,6,7,8,9] , dtype= str)

array(['5', '6', '7', '8', '9'], dtype='<U1')

In [9]:
type(np.asarray([4,5,6,7,8]))

numpy.ndarray

In [10]:
np.asarray([4,5,6,7] , dtype=np.float16)

array([4., 5., 6., 7.], dtype=float16)

In [13]:
mat = np.matrix([5,6])

In [15]:
type(mat)

numpy.matrix

In [16]:
np.asanyarray(mat)

matrix([[5, 6]])

In [17]:
l = [3,4,5,6,7]
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [19]:
np.fromfunction(lambda i ,j : i ==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
np.fromfunction(lambda i ,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [23]:
np.fromfunction(lambda i , j : i ** i , (3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4]], dtype=int32)

In [28]:
np.fromstring("23 56" , sep= "5" ) 

array([23.,  6.])

In [30]:
np.fromstring("4,6" ,sep = ',')

array([4., 6.])

In [31]:
a 

array([5, 6, 7])

In [32]:
a1 = np.array([5,6,7,8,9])

In [33]:
a2 = np.array([[4,5,6,7,8,9]])

In [34]:
a1

array([5, 6, 7, 8, 9])

In [35]:
a2

array([[4, 5, 6, 7, 8, 9]])

In [36]:
a3 = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [37]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a3.ndim

2

In [40]:
a1.ndim

1

In [41]:
a1.size

5

In [42]:
a1

array([5, 6, 7, 8, 9])

In [43]:
a2

array([[4, 5, 6, 7, 8, 9]])

In [44]:
a2.size

6

In [45]:
a3.size


9

In [46]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a1.shape

(5,)

In [48]:
a1

array([5, 6, 7, 8, 9])

In [49]:
a2

array([[4, 5, 6, 7, 8, 9]])

In [50]:
a2.shape

(1, 6)

In [51]:
 a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a3.shape

(3, 3)

In [53]:
np.array([(2,3,4,5,6) ,(3,4,6,7,8)])

array([[2, 3, 4, 5, 6],
       [3, 4, 6, 7, 8]])

In [54]:
range(10)

range(0, 10)

In [55]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
range(3,5.6)

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(3,5.6,.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4])

In [60]:
np.array([(2,3,4,5,6), (3,4,5,6,7)])


array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [65]:
np.fromstring("46562526",sep="2")

array([46562526.])

In [67]:
np.fromstring("23 56", sep = "5")

array([23.,  6.])

In [68]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [70]:
np.linspace(0,9,num = 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
np.linspace(3,5 , num = 5)

array([3. , 3.5, 4. , 4.5, 5. ])

In [72]:
np.zeros(4)

array([0., 0., 0., 0.])

In [74]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
a4 = np.zeros((2,2,3))

In [78]:
a4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
a4.shape


(2, 2, 3)

In [80]:
a4.ndim

3

In [81]:
a4.size

12

In [82]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.ones((3,4)) + 3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [84]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [85]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
np.arange(16).reshape((1,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [92]:
np.arange(16).reshape((16,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [93]:
np.arange(16).reshape((2,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [95]:
np.arange(16).reshape((1,1,2,4,2))

array([[[[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11],
          [12, 13],
          [14, 15]]]]])

In [98]:
np.arange(16).reshape((2,-155643522543))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [99]:
np.arange(16).reshape((2,-3553,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [106]:
np.random.rand(2,3)

array([[0.60014517, 0.51801088, 0.11160628],
       [0.22705487, 0.18693486, 0.05825984]])

In [105]:
np.random.randn(4,5)

array([[-0.69602453, -0.3768545 , -0.9163716 , -0.4235043 ,  0.02902424],
       [ 1.71243638, -0.05281927,  0.12133593,  0.46839721, -0.01418919],
       [ 0.16534258, -0.49000147, -1.52558986, -1.34923549,  1.8111766 ],
       [ 1.52483101,  0.45430118, -1.03079666,  0.21351766,  0.37903316]])

In [125]:
np.random.seed(344646456)
np.random.randint(1,5,(4,3))

array([[3, 4, 4],
       [1, 4, 3],
       [1, 4, 3],
       [1, 1, 4]])

In [127]:
a5 = np.random.randint(2,6 , (3,4))

In [131]:
a5

array([[3, 2, 2, 4],
       [2, 4, 5, 4],
       [4, 4, 4, 5]])

In [134]:
np.sort(a5)

array([[2, 2, 3, 4],
       [2, 4, 4, 5],
       [4, 4, 4, 5]])

In [135]:
np.sort(a5,axis=1)

array([[2, 2, 3, 4],
       [2, 4, 4, 5],
       [4, 4, 4, 5]])

In [133]:
a5

array([[3, 2, 2, 4],
       [2, 4, 5, 4],
       [4, 4, 4, 5]])

In [136]:
a6 = np.random.randint(2,10 , (3,3))

In [137]:
a6

array([[6, 5, 3],
       [6, 8, 4],
       [2, 5, 2]])

In [142]:
np.sort(a6,axis=1,kind = 'mergesort')

array([[3, 5, 6],
       [4, 6, 8],
       [2, 2, 5]])

In [141]:
np.sort(a6,axis=0)

array([[2, 5, 2],
       [6, 5, 3],
       [6, 8, 4]])

In [140]:
np.sort(a6)

array([[3, 5, 6],
       [4, 6, 8],
       [2, 2, 5]])

In [143]:
a6

array([[6, 5, 3],
       [6, 8, 4],
       [2, 5, 2]])

In [144]:
a6.max()

8

In [145]:
a6[2]

array([2, 5, 2])

In [147]:
a6[2:1:1]

array([], shape=(0, 3), dtype=int32)

In [149]:
a7 = np.random.randint(3,7 , (6,6))

In [150]:
a7

array([[5, 4, 4, 5, 6, 6],
       [5, 3, 6, 5, 4, 6],
       [6, 5, 5, 5, 6, 3],
       [3, 6, 4, 5, 6, 3],
       [3, 3, 5, 5, 3, 3],
       [4, 3, 3, 4, 4, 6]])

In [151]:
a7[3]

array([3, 6, 4, 5, 6, 3])

In [154]:
a7[2:5,2:4]

array([[5, 5],
       [4, 5],
       [5, 5]])

In [157]:
a5 = np.random.randint(3,6 , (3,4 ))

In [158]:
a6 = np.random.randint(3,8, (3,4))

In [159]:
a5

array([[4, 4, 4, 5],
       [4, 3, 4, 5],
       [4, 5, 3, 5]])

In [160]:
a6

array([[4, 5, 7, 3],
       [3, 3, 4, 3],
       [4, 5, 4, 5]])

In [161]:
a5/0

<ipython-input-161-bdcb42fa6494>:1: RuntimeWarning: divide by zero encountered in true_divide
  a5/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [162]:
7/0

ZeroDivisionError: division by zero

In [163]:
a5

array([[4, 4, 4, 5],
       [4, 3, 4, 5],
       [4, 5, 3, 5]])

In [164]:
a6

array([[4, 5, 7, 3],
       [3, 3, 4, 3],
       [4, 5, 4, 5]])

In [165]:
a5*a6

array([[16, 20, 28, 15],
       [12,  9, 16, 15],
       [16, 25, 12, 25]])

In [166]:
a5/a6

array([[1.        , 0.8       , 0.57142857, 1.66666667],
       [1.33333333, 1.        , 1.        , 1.66666667],
       [1.        , 1.        , 0.75      , 1.        ]])

In [167]:
a7 = np.random.randint(3,6 , (3,3))

In [168]:
a7

array([[4, 3, 5],
       [3, 4, 3],
       [4, 3, 3]])

In [169]:
a5/a7

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [170]:
a5

array([[4, 4, 4, 5],
       [4, 3, 4, 5],
       [4, 5, 3, 5]])

In [173]:
a6.T

array([[4, 3, 4],
       [5, 3, 5],
       [7, 4, 4],
       [3, 3, 5]])

In [172]:
a7


array([[4, 3, 5],
       [3, 4, 3],
       [4, 3, 3]])

In [174]:
a6.T@a7

array([[41, 36, 41],
       [49, 42, 49],
       [56, 49, 59],
       [41, 36, 39]])

In [175]:
a7

array([[4, 3, 5],
       [3, 4, 3],
       [4, 3, 3]])

In [176]:
a7 ** 3

array([[ 64,  27, 125],
       [ 27,  64,  27],
       [ 64,  27,  27]], dtype=int32)

In [177]:
np.empty((3,6))


array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511562e-306, 6.89805151e-307, 2.56765117e-312]])